main: net.shortninja.staffplus.StaffPlus
name: StaffPlus
version: ${project.version}
description: The ultimate moderation plugin!
author: Shortninja,Qball
softdepend: [PlaceholderAPI, UserLogin ]
api-version: 1.13