main: net.shortninja.staffplus.StaffPlus
name: StaffPlus
version: ${project.version}
description: The ultimate moderation plugin!
author: Shortninja,Qball
depend: [ProtocolLib]
softdepend: [PlaceholderAPI, UserLogin, NBT-API ]
api-version: 1.13